steps:
- name: 'gcr.io/cloud-builders/git'
  args: [ 'fetch','--tags','--unshallow']
- name: 'gcr.io/cloud-builders/git'
  args: [ 'status']
- name: 'gradle:4.9'
  args: [ 'gradle', 'build','-Si','-Panalytics.buildId=$BUILD_ID','-PgithubToken=d495ad9fd75812f5835625300cd476e6988dc5e4']
