steps:
- name: 'gcr.io/cloud-builders/git'
  args: [ 'fetch','--tags']
- name: 'gcr.io/cloud-builders/git'
  args: [ 'status']
- name: 'gcr.io/cloud-builders/gradle'
  args: [ './gradlew', 'build','-Si','-Panalytics.buildId=$BUILD_ID']
