apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: docker:19.03.1-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: zookeeper
      image: confluentinc/cp-zookeeper:5.3.1
      ports:
        - containerPort: 2181
      tty: true
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
    - name: broker
      image: confluentinc/cp-enterprise-kafka:5.3.1
      ports:
        - containerPort: 9092
      tty: true
      env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
    - name: datagen
      image: confluentinc/ksql-examples:5.3.1
      tty: true
      command:
        - "bash -c 'ksql-datagen \
                          bootstrap-server=broker:9092 \
                          quickstart=clickstream_codes \
                          format=json \
                          topic=clickstream_codes \
                          maxInterval=1 \
                          iterations=100 && \
                       ksql-datagen \
                          bootstrap-server=broker:9092 \
                          quickstart=clickstream_users \
                          format=json \
                          topic=clickstream_users \
                          maxInterval=1 \
                          iterations=1000 && \
                       ksql-datagen \
                          bootstrap-server=broker:9092 \
                          quickstart=clickstream \
                          format=json \
                          topic=clickstream \
                          maxInterval=1 \
                          iterations=100 && \
                          cat'"
#    - name: ksqldb-server
#      image: confluentinc/ksqldb-server:0.6.0
#      ports:
#        - containerPort: 8088
#      tty: true
#      env:
#        - name: KSQL_BOOTSTRAP_SERVERS
#          value: broker:9092
#        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
#          value: "true"
#        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
#          value: "true"
#        - name: KSQL_LISTENERS
#          value: http://0.0.0.0:8088
#    - name: ksqldb-cli
#      image: confluentinc/ksqldb-cli:0.6.0
#      command: ['cat']
#      tty: true

