apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: docker:19.03.1-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: confluent
      image: gcr.io/rpa-devops/confluent
      ports:
        - containerPort: 2181
      tty: true
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
