version: 2.0

jobs:
    release:
        machine: true
        branches:
            only:
                - master
        steps:
            - checkout
            - run: ./gradlew release -Prelease.disableChecks -Prelease.localOnly
    build:
        machine: true
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - run: ./gradlew build runAllTests
            - save_cache:
                paths:
                    - ~/.gradle
                    - ~/.m2
                key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
            - store_test_results:
                path: build/test-results
    publish:
        machine: true
        branches:
            only:
                - master
        steps:
            - run: ./gradlew publishPlugins githubRelease
workflows:
    version: 2
    workflow:
        jobs:
            - release
            - build
            - publish