version: 2.0

jobs:
    build:
        machine: true
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: ./gradlew composeUp
            - run: ./gradlew build
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
            - store_test_results:
                path: build/test-results/**/*.xml
