version: 2.1

executors:
  build-test: # declares a reusable executor
    machine: true
    working_directory: ~/workspace

jobs:
    checkout:
        executor: build-test
        steps:
            - checkout
    release:
        executor: build-test
        steps:
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - run: ./gradlew release -Prelease.disableChecks -Prelease.localOnly
    build:
        executor: build-test
        steps:
            - run:
                name: Build and Test
                command: ./gradlew build
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
    test:
        executor: build-test
        steps:
            - run:
                name: Build and Test
                command: ./gradlew build runAllTests
            - save_cache:
                paths:
                    - ~/.gradle
                    - ~/.m2
                key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - store_test_results:
                path: build/test-results
    publish:
        executor: build-test
        steps:
            - run: ./gradlew publishPlugins githubRelease


workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout
      - release:
          requires:
            - checkout
          filters:
            branches:
              only: master
      - build:
          requires:
            - release
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
