name: Build and Publish gradle-confluent Plugin
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release Plugin
      if: github.event_name == 'push'
      run: ./gradlew cleanLibs release -Prelease.disableChecks -Prelease.localOnly -S
    - name: Build Plugin
      run: ./gradlew build -S
    - name: Start Confluent
      run: ./gradlew composeUp -q
    - name: Test Plugin
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./gradlew runAllTests -S
    - name: Publish Plugin
      if: github.event_name == 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./gradlew publishPlugins -S -PgithubToken=${{ secrets.GITHUB_TOKEN }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}