name: Build and Publish gradle-confluent Plugin
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      confluent:
        image: redpillanalytics/docker-confluent
        ports:
        - 8080:8080
        env:
          KSQL_KSQL_SERVICE_ID: kafka-examples
    steps:
    - uses: actions/checkout@master
    - name: Release Plugin
      uses: docker://redpillanalytics/docker-gradle
      with:
        args: cleanLibs release -Prelease.disableChecks -Prelease.localOnly -Si -Prelease.dryRun
