name: Build and Publish gradle-confluent Plugin
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    steps:
    - uses: actions/checkout@master
    - name: Release Plugin
      uses: docker://redpillanalytics/docker-gradle
      with:
        args: cleanLibs release -Prelease.disableChecks -Prelease.localOnly -Si -Prelease.dryRun
