name: Build gradle-confluent Gradle plugin
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: ./gradlew -Si build
