name: Build gradle-confluent Gradle plugin
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Write Google Credential
      run: echo ${{ secrets.GCP_JKEY_TEXT }} > ${{ secrets.GCP_JKEY_PATH }}
    - name: Test Google Credential
      run: cat ${{ secrets.GCP_JKEY_PATH }}
    # - name: Build with Gradle
    #   run: ./gradlew -Si build
