name: Build gradle-confluent Gradle plugin

on: 
  pull_request:
    paths:
    - src/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      uses: docker://redpillanalytics/docker-gradle
      with:
        args: "build -Si"
